# Generated by Django 5.0.6 on 2025-08-01 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="supervisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subordinates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("employee", "员工"),
                    ("manager", "主管"),
                    ("director", "副总"),
                    ("boss", "老总"),
                    ("admin", "管理员"),
                ],
                default="employee",
                max_length=20,
            ),
        ),
    ]
