# Generated by Django 5.0.6 on 2025-08-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_supervisor_alter_user_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="supervisor",
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("employee", "员工"), ("approver", "审批人"), ("admin", "管理员")],
                default="employee",
                max_length=20,
            ),
        ),
    ]
