# Generated by Django 5.0.6 on 2025-07-30 09:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="approver",
        ),
        migrations.AddField(
            model_name="ticket",
            name="approver",
            field=models.ManyToManyField(
                related_name="approvals",
                to=settings.AUTH_USER_MODEL,
                verbose_name="审批人",
            ),
        ),
    ]
