# Generated by Django 5.0.6 on 2025-08-01 02:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0003_approvalrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="work_type",
            field=models.CharField(
                choices=[
                    ("明火作业", "明火作业"),
                    ("高空作业", "高空作业"),
                    ("雾化作业", "雾化作业"),
                    ("动火作业", "动火作业"),
                    ("冷工作业", "冷工作业"),
                    ("电气作业", "电气作业"),
                    ("起重吊装作业", "起重吊装作业"),
                ],
                default=1,
                max_length=50,
                verbose_name="作业类型",
            ),
            preserve_default=False,
        ),
    ]
