# Generated by Django 5.0.6 on 2025-08-01 02:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0004_ticket_work_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="work_type",
        ),
        migrations.AlterField(
            model_name="ticket",
            name="title",
            field=models.CharField(
                choices=[
                    ("repair", "设备维修"),
                    ("purchase", "采购申请"),
                    ("leave", "请假申请"),
                    ("other", "其他事项"),
                ],
                max_length=50,
                verbose_name="工单类型",
            ),
        ),
    ]
