# Generated by Django 5.0.6 on 2025-08-01 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0006_alter_ticket_title"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="approvalrecord",
            options={"ordering": ["order"]},
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="approver",
        ),
        migrations.AddField(
            model_name="approvalrecord",
            name="order",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ticket",
            name="current_approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_approvals",
                to=settings.AUTH_USER_MODEL,
                verbose_name="当前审批人",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="opinion",
            field=models.TextField(blank=True, null=True, verbose_name="最后审批意见"),
        ),
    ]
