# Generated by Django 5.0.6 on 2025-08-01 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "tickets",
            "0007_alter_approvalrecord_options_remove_ticket_approver_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="approvalrecord",
            options={"ordering": ["step"]},
        ),
        migrations.RenameField(
            model_name="approvalrecord",
            old_name="order",
            new_name="step",
        ),
        migrations.AlterUniqueTogether(
            name="approvalrecord",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="applicant",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="current_approver",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="approvalrecord",
            name="processed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="approver_chain",
            field=models.ManyToManyField(
                related_name="tickets_to_approve",
                through="tickets.ApprovalRecord",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="creator",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_tickets",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ticket",
            name="current_step",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="approvalrecord",
            name="status",
            field=models.CharField(
                choices=[("pending", "待处理"), ("approved", "通过"), ("rejected", "驳回")],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="approvalrecord",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tickets.ticket"
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="content",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="opinion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[("pending", "待审批"), ("approved", "已通过"), ("rejected", "已驳回")],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="ticketlog",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name="approvalrecord",
            name="updated_at",
        ),
    ]
