# Generated by Django 5.0.6 on 2025-08-01 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0008_alter_approvalrecord_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="approvalrecord",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="approvalrecord",
            unique_together={("ticket", "approver")},
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="approver_chain",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="current_step",
        ),
        migrations.AddField(
            model_name="approvalrecord",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="applicant",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="申请人",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ticket",
            name="approver",
            field=models.ManyToManyField(
                related_name="approvals",
                to=settings.AUTH_USER_MODEL,
                verbose_name="审批人",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="approvalrecord",
            name="status",
            field=models.CharField(
                choices=[("pending", "待审批"), ("approved", "已通过"), ("rejected", "驳回")],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="approvalrecord",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_records",
                to="tickets.ticket",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="content",
            field=models.TextField(verbose_name="工单内容"),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="opinion",
            field=models.TextField(blank=True, null=True, verbose_name="审批意见"),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待审批"),
                    ("approved", "已通过"),
                    ("rejected", "被驳回"),
                    ("archived", "已归档"),
                ],
                default="pending",
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="title",
            field=models.CharField(
                choices=[
                    ("明火作业", "明火作业"),
                    ("高空作业", "高空作业"),
                    ("雾化作业", "雾化作业"),
                    ("动火作业", "动火作业"),
                    ("冷工作业", "冷工作业"),
                    ("电气作业", "电气作业"),
                    ("起重吊装作业", "起重吊装作业"),
                ],
                max_length=50,
                verbose_name="工单类型",
            ),
        ),
        migrations.AlterField(
            model_name="ticketlog",
            name="message",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="approvalrecord",
            name="processed_at",
        ),
        migrations.RemoveField(
            model_name="approvalrecord",
            name="step",
        ),
    ]
