# Generated by Django 5.0.6 on 2025-08-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0009_alter_approvalrecord_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="approvalrecord",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="approvalrecord",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
