# Generated by Django 5.0.6 on 2025-08-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0010_alter_approvalrecord_options_approvalrecord_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="attachments",
            field=models.TextField(blank=True, null=True, verbose_name="附件"),
        ),
        migrations.AddField(
            model_name="ticket",
            name="attention",
            field=models.TextField(default="注意安全", verbose_name="注意事项"),
        ),
        migrations.AddField(
            model_name="ticket",
            name="emergency_measures",
            field=models.TextField(default="无", verbose_name="应急措施"),
        ),
        migrations.AddField(
            model_name="ticket",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="结束时间"),
        ),
        migrations.AddField(
            model_name="ticket",
            name="leader",
            field=models.CharField(default="未指定", max_length=50, verbose_name="负责人"),
        ),
        migrations.AddField(
            model_name="ticket",
            name="location",
            field=models.CharField(default="本厂区", max_length=200, verbose_name="作业地点"),
        ),
        migrations.AddField(
            model_name="ticket",
            name="protection_measures",
            field=models.TextField(blank=True, null=True, verbose_name="安全防护措施"),
        ),
        migrations.AddField(
            model_name="ticket",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
        ),
        migrations.AddField(
            model_name="ticket",
            name="workers",
            field=models.TextField(blank=True, null=True, verbose_name="作业人员"),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="content",
            field=models.TextField(blank=True, null=True, verbose_name="作业内容"),
        ),
    ]
